apiVersion: v1
kind: Service
metadata:
  name: airdb
spec:
  selector:
    app: airdb
  ports:
    - port: 5432
      targetPort: postgres-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airdb
spec:
  selector:
    matchLabels:
      app: airdb
  serviceName: airdb
  replicas: 1
  template:
    metadata:
      labels:
        app: airdb
    spec:
      containers:
        - name: airdb
          image: airdb-image
          env:
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: airdb-pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: airdb-pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Mi